[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.1"
actix-web = "4.5.1"
actix-cors = "0.7.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
dotenv = "0.15.0"

auth-2fa = { path="../" }